require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"SpeechSynth":[function(require,module,exports){
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.SpeechSynth = (function(superClass) {
  extend(SpeechSynth, superClass);

  function SpeechSynth(options) {
    var option;
    if (options == null) {
      options = {};
    }
    this._utterance = new SpeechSynthesisUtterance();
    this._voices = window.speechSynthesis.getVoices();
    if (options.voice) {
      options.voice = this._voices.filter(function(voice) {
        return voice.name === ("" + options.voice);
      })[0];
    }
    for (option in options) {
      this._utterance["" + option] = options["" + option];
    }
  }

  SpeechSynth.prototype.speak = function() {
    return window.speechSynthesis.speak(this._utterance);
  };

  SpeechSynth.prototype.cancel = function() {
    return window.speechSynthesis.cancel(this._utterance);
  };

  SpeechSynth.prototype.pause = function() {
    return window.speechSynthesis.pause(this._utterance);
  };

  SpeechSynth.prototype.resume = function() {
    return window.speechSynthesis.resume(this._utterance);
  };

  SpeechSynth.define("voices", {
    get: function() {
      var i, len, ref, voice, voices;
      voices = [];
      ref = this._voices;
      for (i = 0, len = ref.length; i < len; i++) {
        voice = ref[i];
        voices[_.indexOf(this._voices, voice)] = voice.name;
      }
      return voices;
    }
  });

  SpeechSynth.define("isPending", {
    get: function() {
      return window.speechSynthesis.pending;
    }
  });

  SpeechSynth.define("isSpeaking", {
    get: function() {
      return window.speechSynthesis.speaking;
    }
  });

  SpeechSynth.define("isPaused", {
    get: function() {
      return window.speechSynthesis.paused;
    }
  });

  SpeechSynth.define("text", {
    get: function() {
      return this._utterance.text;
    },
    set: function(value) {
      return this._utterance.text = value;
    }
  });

  SpeechSynth.define("lang", {
    get: function() {
      return this._utterance.lang;
    },
    set: function(value) {
      return this._utterance.lang = value;
    }
  });

  SpeechSynth.define("volume", {
    get: function() {
      return this._utterance.volume;
    },
    set: function(value) {
      return this._utterance.volume = value;
    }
  });

  SpeechSynth.define("rate", {
    get: function() {
      return this._utterance.rate;
    },
    set: function(value) {
      return this._utterance.rate = value;
    }
  });

  SpeechSynth.define("pitch", {
    get: function() {
      return this._utterance.pitch;
    },
    set: function(value) {
      return this._utterance.pitch = value;
    }
  });

  return SpeechSynth;

})(Framer.BaseClass);



},{}],"SpeechSynth":[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.SpeechSynth = (function(superClass) {
  extend(SpeechSynth, superClass);

  function SpeechSynth(options) {
    var option;
    if (options == null) {
      options = {};
    }
    this._utterance = new SpeechSynthesisUtterance();
    this._voices = window.speechSynthesis.getVoices();
    if (options.voice) {
      options.voice = this._voices.filter(function(voice) {
        return voice.name === ("" + options.voice);
      })[0];
    }
    for (option in options) {
      this._utterance["" + option] = options["" + option];
    }
  }

  SpeechSynth.prototype.speak = function() {
    return window.speechSynthesis.speak(this._utterance);
  };

  SpeechSynth.prototype.cancel = function() {
    return window.speechSynthesis.cancel(this._utterance);
  };

  SpeechSynth.prototype.pause = function() {
    return window.speechSynthesis.pause(this._utterance);
  };

  SpeechSynth.prototype.resume = function() {
    return window.speechSynthesis.resume(this._utterance);
  };

  SpeechSynth.define("voices", {
    get: function() {
      var i, len, ref, voice, voices;
      voices = [];
      ref = this._voices;
      for (i = 0, len = ref.length; i < len; i++) {
        voice = ref[i];
        voices[_.indexOf(this._voices, voice)] = voice.name;
      }
      return voices;
    }
  });

  SpeechSynth.define("isPending", {
    get: function() {
      return window.speechSynthesis.pending;
    }
  });

  SpeechSynth.define("isSpeaking", {
    get: function() {
      return window.speechSynthesis.speaking;
    }
  });

  SpeechSynth.define("isPaused", {
    get: function() {
      return window.speechSynthesis.paused;
    }
  });

  SpeechSynth.define("text", {
    get: function() {
      return this._utterance.text;
    },
    set: function(value) {
      return this._utterance.text = value;
    }
  });

  SpeechSynth.define("lang", {
    get: function() {
      return this._utterance.lang;
    },
    set: function(value) {
      return this._utterance.lang = value;
    }
  });

  SpeechSynth.define("volume", {
    get: function() {
      return this._utterance.volume;
    },
    set: function(value) {
      return this._utterance.volume = value;
    }
  });

  SpeechSynth.define("rate", {
    get: function() {
      return this._utterance.rate;
    },
    set: function(value) {
      return this._utterance.rate = value;
    }
  });

  SpeechSynth.define("pitch", {
    get: function() {
      return this._utterance.pitch;
    },
    set: function(value) {
      return this._utterance.pitch = value;
    }
  });

  return SpeechSynth;

})(Framer.BaseClass);

},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvVXNlcnMvam9zaG10dWNrZXIvR2l0SHViL0FmcmljYW5BbmltYWxzLmZyYW1lci9tb2R1bGVzL1NwZWVjaFN5bnRoLmNvZmZlZSIsIi4uLy4uLy4uLy4uLy4uL1VzZXJzL2pvc2htdHVja2VyL0dpdEh1Yi9BZnJpY2FuQW5pbWFscy5mcmFtZXIvbW9kdWxlcy9TcGVlY2hTeW50aC5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQ0FBLElBQUE7NkJBQUE7O0FBQUEsT0FBYSxDQUFDO0FBQ2IsaUNBQUEsQ0FBQTs7QUFBYSxFQUFBLHFCQUFDLE9BQUQsR0FBQTtBQUNaLFFBQUEsTUFBQTs7TUFEYSxVQUFRO0tBQ3JCO0FBQUEsSUFBQSxJQUFDLENBQUEsVUFBRCxHQUFrQixJQUFBLHdCQUFBLENBQUEsQ0FBbEIsQ0FBQTtBQUFBLElBQ0EsSUFBQyxDQUFBLE9BQUQsR0FBVyxNQUFNLENBQUMsZUFBZSxDQUFDLFNBQXZCLENBQUEsQ0FEWCxDQUFBO0FBR0EsSUFBQSxJQUFHLE9BQU8sQ0FBQyxLQUFYO0FBQ0MsTUFBQSxPQUFPLENBQUMsS0FBUixHQUFnQixJQUFDLENBQUEsT0FBTyxDQUFDLE1BQVQsQ0FBZ0IsU0FBQyxLQUFELEdBQUE7ZUFBVyxLQUFLLENBQUMsSUFBTixLQUFjLENBQUEsRUFBQSxHQUFHLE9BQU8sQ0FBQyxLQUFYLEVBQXpCO01BQUEsQ0FBaEIsQ0FBNkQsQ0FBQSxDQUFBLENBQTdFLENBREQ7S0FIQTtBQU1BLFNBQUEsaUJBQUEsR0FBQTtBQUNDLE1BQUEsSUFBQyxDQUFBLFVBQVcsQ0FBQSxFQUFBLEdBQUcsTUFBSCxDQUFaLEdBQTJCLE9BQVEsQ0FBQSxFQUFBLEdBQUcsTUFBSCxDQUFuQyxDQUREO0FBQUEsS0FQWTtFQUFBLENBQWI7O0FBQUEsd0JBVUEsS0FBQSxHQUFPLFNBQUEsR0FBQTtXQUNOLE1BQU0sQ0FBQyxlQUFlLENBQUMsS0FBdkIsQ0FBNkIsSUFBQyxDQUFBLFVBQTlCLEVBRE07RUFBQSxDQVZQLENBQUE7O0FBQUEsd0JBYUEsTUFBQSxHQUFRLFNBQUEsR0FBQTtXQUNQLE1BQU0sQ0FBQyxlQUFlLENBQUMsTUFBdkIsQ0FBOEIsSUFBQyxDQUFBLFVBQS9CLEVBRE87RUFBQSxDQWJSLENBQUE7O0FBQUEsd0JBZ0JBLEtBQUEsR0FBTyxTQUFBLEdBQUE7V0FDTixNQUFNLENBQUMsZUFBZSxDQUFDLEtBQXZCLENBQTZCLElBQUMsQ0FBQSxVQUE5QixFQURNO0VBQUEsQ0FoQlAsQ0FBQTs7QUFBQSx3QkFtQkEsTUFBQSxHQUFRLFNBQUEsR0FBQTtXQUNQLE1BQU0sQ0FBQyxlQUFlLENBQUMsTUFBdkIsQ0FBOEIsSUFBQyxDQUFBLFVBQS9CLEVBRE87RUFBQSxDQW5CUixDQUFBOztBQUFBLEVBc0JBLFdBQUMsQ0FBQSxNQUFELENBQVEsUUFBUixFQUNDO0FBQUEsSUFBQSxHQUFBLEVBQUssU0FBQSxHQUFBO0FBQ0osVUFBQSwwQkFBQTtBQUFBLE1BQUEsTUFBQSxHQUFTLEVBQVQsQ0FBQTtBQUVBO0FBQUEsV0FBQSxxQ0FBQTt1QkFBQTtBQUNDLFFBQUEsTUFBTyxDQUFBLENBQUMsQ0FBQyxPQUFGLENBQVUsSUFBQyxDQUFBLE9BQVgsRUFBb0IsS0FBcEIsQ0FBQSxDQUFQLEdBQXFDLEtBQUssQ0FBQyxJQUEzQyxDQUREO0FBQUEsT0FGQTtBQUtBLGFBQU8sTUFBUCxDQU5JO0lBQUEsQ0FBTDtHQURELENBdEJBLENBQUE7O0FBQUEsRUErQkEsV0FBQyxDQUFBLE1BQUQsQ0FBUSxXQUFSLEVBQ0M7QUFBQSxJQUFBLEdBQUEsRUFBSyxTQUFBLEdBQUE7YUFBRyxNQUFNLENBQUMsZUFBZSxDQUFDLFFBQTFCO0lBQUEsQ0FBTDtHQURELENBL0JBLENBQUE7O0FBQUEsRUFpQ0EsV0FBQyxDQUFBLE1BQUQsQ0FBUSxZQUFSLEVBQ0M7QUFBQSxJQUFBLEdBQUEsRUFBSyxTQUFBLEdBQUE7YUFBRyxNQUFNLENBQUMsZUFBZSxDQUFDLFNBQTFCO0lBQUEsQ0FBTDtHQURELENBakNBLENBQUE7O0FBQUEsRUFtQ0EsV0FBQyxDQUFBLE1BQUQsQ0FBUSxVQUFSLEVBQ0M7QUFBQSxJQUFBLEdBQUEsRUFBSyxTQUFBLEdBQUE7YUFBRyxNQUFNLENBQUMsZUFBZSxDQUFDLE9BQTFCO0lBQUEsQ0FBTDtHQURELENBbkNBLENBQUE7O0FBQUEsRUFxQ0EsV0FBQyxDQUFBLE1BQUQsQ0FBUSxNQUFSLEVBQ0M7QUFBQSxJQUFBLEdBQUEsRUFBSyxTQUFBLEdBQUE7YUFBRyxJQUFDLENBQUEsVUFBVSxDQUFDLEtBQWY7SUFBQSxDQUFMO0FBQUEsSUFDQSxHQUFBLEVBQUssU0FBQyxLQUFELEdBQUE7YUFBVyxJQUFDLENBQUEsVUFBVSxDQUFDLElBQVosR0FBbUIsTUFBOUI7SUFBQSxDQURMO0dBREQsQ0FyQ0EsQ0FBQTs7QUFBQSxFQXdDQSxXQUFDLENBQUEsTUFBRCxDQUFRLE1BQVIsRUFDQztBQUFBLElBQUEsR0FBQSxFQUFLLFNBQUEsR0FBQTthQUFHLElBQUMsQ0FBQSxVQUFVLENBQUMsS0FBZjtJQUFBLENBQUw7QUFBQSxJQUNBLEdBQUEsRUFBSyxTQUFDLEtBQUQsR0FBQTthQUFXLElBQUMsQ0FBQSxVQUFVLENBQUMsSUFBWixHQUFtQixNQUE5QjtJQUFBLENBREw7R0FERCxDQXhDQSxDQUFBOztBQUFBLEVBMkNBLFdBQUMsQ0FBQSxNQUFELENBQVEsUUFBUixFQUNDO0FBQUEsSUFBQSxHQUFBLEVBQUssU0FBQSxHQUFBO2FBQUcsSUFBQyxDQUFBLFVBQVUsQ0FBQyxPQUFmO0lBQUEsQ0FBTDtBQUFBLElBQ0EsR0FBQSxFQUFLLFNBQUMsS0FBRCxHQUFBO2FBQVcsSUFBQyxDQUFBLFVBQVUsQ0FBQyxNQUFaLEdBQXFCLE1BQWhDO0lBQUEsQ0FETDtHQURELENBM0NBLENBQUE7O0FBQUEsRUE4Q0EsV0FBQyxDQUFBLE1BQUQsQ0FBUSxNQUFSLEVBQ0M7QUFBQSxJQUFBLEdBQUEsRUFBSyxTQUFBLEdBQUE7YUFBRyxJQUFDLENBQUEsVUFBVSxDQUFDLEtBQWY7SUFBQSxDQUFMO0FBQUEsSUFDQSxHQUFBLEVBQUssU0FBQyxLQUFELEdBQUE7YUFBVyxJQUFDLENBQUEsVUFBVSxDQUFDLElBQVosR0FBbUIsTUFBOUI7SUFBQSxDQURMO0dBREQsQ0E5Q0EsQ0FBQTs7QUFBQSxFQWlEQSxXQUFDLENBQUEsTUFBRCxDQUFRLE9BQVIsRUFDQztBQUFBLElBQUEsR0FBQSxFQUFLLFNBQUEsR0FBQTthQUFHLElBQUMsQ0FBQSxVQUFVLENBQUMsTUFBZjtJQUFBLENBQUw7QUFBQSxJQUNBLEdBQUEsRUFBSyxTQUFDLEtBQUQsR0FBQTthQUFXLElBQUMsQ0FBQSxVQUFVLENBQUMsS0FBWixHQUFvQixNQUEvQjtJQUFBLENBREw7R0FERCxDQWpEQSxDQUFBOztxQkFBQTs7R0FEaUMsTUFBTSxDQUFDLFVBQXpDLENBQUE7Ozs7O0FDQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzQ29udGVudCI6WyIoZnVuY3Rpb24gZSh0LG4scil7ZnVuY3Rpb24gcyhvLHUpe2lmKCFuW29dKXtpZighdFtvXSl7dmFyIGE9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtpZighdSYmYSlyZXR1cm4gYShvLCEwKTtpZihpKXJldHVybiBpKG8sITApO3ZhciBmPW5ldyBFcnJvcihcIkNhbm5vdCBmaW5kIG1vZHVsZSAnXCIrbytcIidcIik7dGhyb3cgZi5jb2RlPVwiTU9EVUxFX05PVF9GT1VORFwiLGZ9dmFyIGw9bltvXT17ZXhwb3J0czp7fX07dFtvXVswXS5jYWxsKGwuZXhwb3J0cyxmdW5jdGlvbihlKXt2YXIgbj10W29dWzFdW2VdO3JldHVybiBzKG4/bjplKX0sbCxsLmV4cG9ydHMsZSx0LG4scil9cmV0dXJuIG5bb10uZXhwb3J0c312YXIgaT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2Zvcih2YXIgbz0wO288ci5sZW5ndGg7bysrKXMocltvXSk7cmV0dXJuIHN9KSIsImNsYXNzIGV4cG9ydHMuU3BlZWNoU3ludGggZXh0ZW5kcyBGcmFtZXIuQmFzZUNsYXNzXG5cdGNvbnN0cnVjdG9yOiAob3B0aW9ucz17fSkgLT5cblx0XHRAX3V0dGVyYW5jZSA9IG5ldyBTcGVlY2hTeW50aGVzaXNVdHRlcmFuY2UoKVxuXHRcdEBfdm9pY2VzID0gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5nZXRWb2ljZXMoKVxuXG5cdFx0aWYgb3B0aW9ucy52b2ljZVxuXHRcdFx0b3B0aW9ucy52b2ljZSA9IEBfdm9pY2VzLmZpbHRlcigodm9pY2UpIC0+IHZvaWNlLm5hbWUgPT0gXCIje29wdGlvbnMudm9pY2V9XCIpWzBdXG5cblx0XHRmb3Igb3B0aW9uIG9mIG9wdGlvbnNcblx0XHRcdEBfdXR0ZXJhbmNlW1wiI3tvcHRpb259XCJdID0gb3B0aW9uc1tcIiN7b3B0aW9ufVwiXVxuXG5cdHNwZWFrOiAtPlxuXHRcdHdpbmRvdy5zcGVlY2hTeW50aGVzaXMuc3BlYWsoQF91dHRlcmFuY2UpXG5cblx0Y2FuY2VsOiAtPlxuXHRcdHdpbmRvdy5zcGVlY2hTeW50aGVzaXMuY2FuY2VsKEBfdXR0ZXJhbmNlKVxuXG5cdHBhdXNlOiAtPlxuXHRcdHdpbmRvdy5zcGVlY2hTeW50aGVzaXMucGF1c2UoQF91dHRlcmFuY2UpXG5cblx0cmVzdW1lOiAtPlxuXHRcdHdpbmRvdy5zcGVlY2hTeW50aGVzaXMucmVzdW1lKEBfdXR0ZXJhbmNlKVxuXG5cdEBkZWZpbmUgXCJ2b2ljZXNcIixcblx0XHRnZXQ6IC0+IFxuXHRcdFx0dm9pY2VzID0gW11cblx0XHRcdFxuXHRcdFx0Zm9yIHZvaWNlIGluIEBfdm9pY2VzXG5cdFx0XHRcdHZvaWNlc1tfLmluZGV4T2YoQF92b2ljZXMsIHZvaWNlKV0gPSB2b2ljZS5uYW1lIFxuXG5cdFx0XHRyZXR1cm4gdm9pY2VzXG5cblx0QGRlZmluZSBcImlzUGVuZGluZ1wiLFxuXHRcdGdldDogLT4gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5wZW5kaW5nXG5cdEBkZWZpbmUgXCJpc1NwZWFraW5nXCIsXG5cdFx0Z2V0OiAtPiB3aW5kb3cuc3BlZWNoU3ludGhlc2lzLnNwZWFraW5nXG5cdEBkZWZpbmUgXCJpc1BhdXNlZFwiLCBcblx0XHRnZXQ6IC0+IHdpbmRvdy5zcGVlY2hTeW50aGVzaXMucGF1c2VkXG5cdEBkZWZpbmUgXCJ0ZXh0XCIsXG5cdFx0Z2V0OiAtPiBAX3V0dGVyYW5jZS50ZXh0XG5cdFx0c2V0OiAodmFsdWUpIC0+IEBfdXR0ZXJhbmNlLnRleHQgPSB2YWx1ZVxuXHRAZGVmaW5lIFwibGFuZ1wiLFxuXHRcdGdldDogLT4gQF91dHRlcmFuY2UubGFuZ1xuXHRcdHNldDogKHZhbHVlKSAtPiBAX3V0dGVyYW5jZS5sYW5nID0gdmFsdWVcblx0QGRlZmluZSBcInZvbHVtZVwiLFxuXHRcdGdldDogLT4gQF91dHRlcmFuY2Uudm9sdW1lXG5cdFx0c2V0OiAodmFsdWUpIC0+IEBfdXR0ZXJhbmNlLnZvbHVtZSA9IHZhbHVlXG5cdEBkZWZpbmUgXCJyYXRlXCIsXG5cdFx0Z2V0OiAtPiBAX3V0dGVyYW5jZS5yYXRlXG5cdFx0c2V0OiAodmFsdWUpIC0+IEBfdXR0ZXJhbmNlLnJhdGUgPSB2YWx1ZVxuXHRAZGVmaW5lIFwicGl0Y2hcIixcblx0XHRnZXQ6IC0+IEBfdXR0ZXJhbmNlLnBpdGNoXG5cdFx0c2V0OiAodmFsdWUpIC0+IEBfdXR0ZXJhbmNlLnBpdGNoID0gdmFsdWVcbiIsIi8vIEdlbmVyYXRlZCBieSBDb2ZmZWVTY3JpcHQgMS45LjFcbnZhciBleHRlbmQgPSBmdW5jdGlvbihjaGlsZCwgcGFyZW50KSB7IGZvciAodmFyIGtleSBpbiBwYXJlbnQpIHsgaWYgKGhhc1Byb3AuY2FsbChwYXJlbnQsIGtleSkpIGNoaWxkW2tleV0gPSBwYXJlbnRba2V5XTsgfSBmdW5jdGlvbiBjdG9yKCkgeyB0aGlzLmNvbnN0cnVjdG9yID0gY2hpbGQ7IH0gY3Rvci5wcm90b3R5cGUgPSBwYXJlbnQucHJvdG90eXBlOyBjaGlsZC5wcm90b3R5cGUgPSBuZXcgY3RvcigpOyBjaGlsZC5fX3N1cGVyX18gPSBwYXJlbnQucHJvdG90eXBlOyByZXR1cm4gY2hpbGQ7IH0sXG4gIGhhc1Byb3AgPSB7fS5oYXNPd25Qcm9wZXJ0eTtcblxuZXhwb3J0cy5TcGVlY2hTeW50aCA9IChmdW5jdGlvbihzdXBlckNsYXNzKSB7XG4gIGV4dGVuZChTcGVlY2hTeW50aCwgc3VwZXJDbGFzcyk7XG5cbiAgZnVuY3Rpb24gU3BlZWNoU3ludGgob3B0aW9ucykge1xuICAgIHZhciBvcHRpb247XG4gICAgaWYgKG9wdGlvbnMgPT0gbnVsbCkge1xuICAgICAgb3B0aW9ucyA9IHt9O1xuICAgIH1cbiAgICB0aGlzLl91dHRlcmFuY2UgPSBuZXcgU3BlZWNoU3ludGhlc2lzVXR0ZXJhbmNlKCk7XG4gICAgdGhpcy5fdm9pY2VzID0gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5nZXRWb2ljZXMoKTtcbiAgICBpZiAob3B0aW9ucy52b2ljZSkge1xuICAgICAgb3B0aW9ucy52b2ljZSA9IHRoaXMuX3ZvaWNlcy5maWx0ZXIoZnVuY3Rpb24odm9pY2UpIHtcbiAgICAgICAgcmV0dXJuIHZvaWNlLm5hbWUgPT09IChcIlwiICsgb3B0aW9ucy52b2ljZSk7XG4gICAgICB9KVswXTtcbiAgICB9XG4gICAgZm9yIChvcHRpb24gaW4gb3B0aW9ucykge1xuICAgICAgdGhpcy5fdXR0ZXJhbmNlW1wiXCIgKyBvcHRpb25dID0gb3B0aW9uc1tcIlwiICsgb3B0aW9uXTtcbiAgICB9XG4gIH1cblxuICBTcGVlY2hTeW50aC5wcm90b3R5cGUuc3BlYWsgPSBmdW5jdGlvbigpIHtcbiAgICByZXR1cm4gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5zcGVhayh0aGlzLl91dHRlcmFuY2UpO1xuICB9O1xuXG4gIFNwZWVjaFN5bnRoLnByb3RvdHlwZS5jYW5jZWwgPSBmdW5jdGlvbigpIHtcbiAgICByZXR1cm4gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5jYW5jZWwodGhpcy5fdXR0ZXJhbmNlKTtcbiAgfTtcblxuICBTcGVlY2hTeW50aC5wcm90b3R5cGUucGF1c2UgPSBmdW5jdGlvbigpIHtcbiAgICByZXR1cm4gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5wYXVzZSh0aGlzLl91dHRlcmFuY2UpO1xuICB9O1xuXG4gIFNwZWVjaFN5bnRoLnByb3RvdHlwZS5yZXN1bWUgPSBmdW5jdGlvbigpIHtcbiAgICByZXR1cm4gd2luZG93LnNwZWVjaFN5bnRoZXNpcy5yZXN1bWUodGhpcy5fdXR0ZXJhbmNlKTtcbiAgfTtcblxuICBTcGVlY2hTeW50aC5kZWZpbmUoXCJ2b2ljZXNcIiwge1xuICAgIGdldDogZnVuY3Rpb24oKSB7XG4gICAgICB2YXIgaSwgbGVuLCByZWYsIHZvaWNlLCB2b2ljZXM7XG4gICAgICB2b2ljZXMgPSBbXTtcbiAgICAgIHJlZiA9IHRoaXMuX3ZvaWNlcztcbiAgICAgIGZvciAoaSA9IDAsIGxlbiA9IHJlZi5sZW5ndGg7IGkgPCBsZW47IGkrKykge1xuICAgICAgICB2b2ljZSA9IHJlZltpXTtcbiAgICAgICAgdm9pY2VzW18uaW5kZXhPZih0aGlzLl92b2ljZXMsIHZvaWNlKV0gPSB2b2ljZS5uYW1lO1xuICAgICAgfVxuICAgICAgcmV0dXJuIHZvaWNlcztcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcImlzUGVuZGluZ1wiLCB7XG4gICAgZ2V0OiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiB3aW5kb3cuc3BlZWNoU3ludGhlc2lzLnBlbmRpbmc7XG4gICAgfVxuICB9KTtcblxuICBTcGVlY2hTeW50aC5kZWZpbmUoXCJpc1NwZWFraW5nXCIsIHtcbiAgICBnZXQ6IGZ1bmN0aW9uKCkge1xuICAgICAgcmV0dXJuIHdpbmRvdy5zcGVlY2hTeW50aGVzaXMuc3BlYWtpbmc7XG4gICAgfVxuICB9KTtcblxuICBTcGVlY2hTeW50aC5kZWZpbmUoXCJpc1BhdXNlZFwiLCB7XG4gICAgZ2V0OiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiB3aW5kb3cuc3BlZWNoU3ludGhlc2lzLnBhdXNlZDtcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcInRleHRcIiwge1xuICAgIGdldDogZnVuY3Rpb24oKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLnRleHQ7XG4gICAgfSxcbiAgICBzZXQ6IGZ1bmN0aW9uKHZhbHVlKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLnRleHQgPSB2YWx1ZTtcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcImxhbmdcIiwge1xuICAgIGdldDogZnVuY3Rpb24oKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLmxhbmc7XG4gICAgfSxcbiAgICBzZXQ6IGZ1bmN0aW9uKHZhbHVlKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLmxhbmcgPSB2YWx1ZTtcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcInZvbHVtZVwiLCB7XG4gICAgZ2V0OiBmdW5jdGlvbigpIHtcbiAgICAgIHJldHVybiB0aGlzLl91dHRlcmFuY2Uudm9sdW1lO1xuICAgIH0sXG4gICAgc2V0OiBmdW5jdGlvbih2YWx1ZSkge1xuICAgICAgcmV0dXJuIHRoaXMuX3V0dGVyYW5jZS52b2x1bWUgPSB2YWx1ZTtcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcInJhdGVcIiwge1xuICAgIGdldDogZnVuY3Rpb24oKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLnJhdGU7XG4gICAgfSxcbiAgICBzZXQ6IGZ1bmN0aW9uKHZhbHVlKSB7XG4gICAgICByZXR1cm4gdGhpcy5fdXR0ZXJhbmNlLnJhdGUgPSB2YWx1ZTtcbiAgICB9XG4gIH0pO1xuXG4gIFNwZWVjaFN5bnRoLmRlZmluZShcInBpdGNoXCIsIHtcbiAgICBnZXQ6IGZ1bmN0aW9uKCkge1xuICAgICAgcmV0dXJuIHRoaXMuX3V0dGVyYW5jZS5waXRjaDtcbiAgICB9LFxuICAgIHNldDogZnVuY3Rpb24odmFsdWUpIHtcbiAgICAgIHJldHVybiB0aGlzLl91dHRlcmFuY2UucGl0Y2ggPSB2YWx1ZTtcbiAgICB9XG4gIH0pO1xuXG4gIHJldHVybiBTcGVlY2hTeW50aDtcblxufSkoRnJhbWVyLkJhc2VDbGFzcyk7XG4iXX0=
